# Book settings
title: Lab in C&P (Spring2021)
author: Todd M. Gureckis
logo: images/logo/artificialintelligence.svg

html:
  home_page_in_navbar: false

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: off

parse:
  myst_extended_syntax: true

repository:
  url: https://github.com/gureckis/nyu_lab_in_cognition
  path_to_book: book/
  branch: master


launch_buttons:
  notebook_interface: "classic"
  jupyterhub_url: "https://psychua-46002-spring.rcnyu.org/"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
